const SETUSER = 'SETUSER'
const REMOVEUSER = 'REMOVEUSER'

//call
const CALLACCEPTED = 'CALLACCEPTED'

const SETPEER = 'SETPEER'
const SETSTREAM = 'SETSTREAM'

export default {}
export { SETUSER, REMOVEUSER, CALLACCEPTED, SETPEER, SETSTREAM }