const SETUSER = 'SETUSER'
const REMOVEUSER = 'REMOVEUSER'

//call
const CALLACCEPTED = 'CALLACCEPTED'

const SETPEER = 'SETPEER'
const SETSTREAM = 'SETSTREAM'

// meeting participants
const MEETINGPARTICIPANTS = 'MEETINGPARTICIPANTS'
const REMOVEPARTICIPANT = 'REMOVEPARTICIPANT'

// meeting chat
const SETMESSAGE = 'SETMESSAGE'
const SETMESSAGES = 'SETMESSAGES'

export default {}
export { SETUSER,
     REMOVEUSER, 
     CALLACCEPTED, 
     SETPEER, 
     SETSTREAM, 
     MEETINGPARTICIPANTS, 
     REMOVEPARTICIPANT, 
     SETMESSAGE, 
     SETMESSAGES 
}