const SETUSER = 'SETUSER'
const REMOVEUSER = 'REMOVEUSER'

// meeting participants
const MEETINGPARTICIPANTS = 'MEETINGPARTICIPANTS'
const REMOVEPARTICIPANT = 'REMOVEPARTICIPANT'

// meeting chat
const SETMESSAGE = 'SETMESSAGE'
const SETMESSAGES = 'SETMESSAGES'

export default {}
export { SETUSER,
     REMOVEUSER, 
     MEETINGPARTICIPANTS, 
     REMOVEPARTICIPANT, 
     SETMESSAGE, 
     SETMESSAGES 
}